[package]
name = "blaze"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
overflow-checks = false
lto = true
strip = "symbols"

[dependencies]
cheatlib = { git = "https://github.com/implicitlycorrect/cheatlib" }
