[package]
name = "blaze"
version = "0.1.0"
edition = "2021"

[lib]
name = "blaze"
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
cheatlib = { git = "https://github.com/implicitlycorrect/cheatlib", features = [
    "console",
    "internal"
] }
lazy_static = "1.4"
